name: Test CI

on: [push, pull_request]

jobs:
  format-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: "Code format check."
        run: python3 -m black --check src
      - name: "Typing check."
        run: python3 -m mypy src
      - name: "Unit tests."
        run: python3 -m pytest
